INSERT INTO tbl_department VALUES ("Department of Oriental Studies", "\tThis is one of the oldest Departments of the University as it came into existence together with the University in 1920.There are Tutors, AssistantLecturers, Lecturers, and a Professor in the Department. Three part-time Professors andthree Venerable Sayadaws from the International Theravada Buddhist Missionary University and one Venerable Sayadaw from the State Pariyatti Sasana University are acting as part time Lecturers.\n\n\tThe Department offers courses leading to the degree of Master of Arts, Master of Research and Doctor of Philosophy (Ph.D) in Oriental Studies.\n\n\tThe Doctoral programme was introduced in 1999 and currentlythere are 44 candidates doing research in the field of Pali literature and other allied subjects. Another batch of seven students is attending the one-year preliminary course before doing their dissertations. There are 24 teaching staffs in the Department and there is an in-house library for the staff and researchers. The teaching staffs are also tasked to do researches of academic anddevelopmental nature. The Department of Oriental Studies also offers a 9-month Diploma Course known as Diploma for Oriental Studies (DOS) under the Yangon University Centre for Human Resource Development.", "os");
ALTER TABLE tbl_department ADD location CHAR;
UPDATE tbl_department SET name = "Department of Mathematics" WHERE name = "Department of Mathematics ";
UPDATE tbl_department SET name = "Department of Geology" WHERE name = "Department of Geology ";
UPDATE tbl_department SET name = "Department of Geography" WHERE name = "Department of Geography ";
UPDATE tbl_department SET name = "Department of English"  WHERE name = "Department of English ";
UPDATE tbl_department SET name = "Department of International Relationship" WHERE name = "Department of International Realtionship";
UPDATE tbl_department SET name = "Department of Chemistry" WHERE name = "Department of Chemistry ";
UPDATE tbl_department SET location = "University Lab Building" WHERE name = "Department of Computer Studies";
UPDATE tbl_department SET location = "University Lab Building" WHERE name = "Department of Industrial Chemistry";
UPDATE tbl_department SET location = "Taungu Hall" WHERE name = "Department of Myanmar";
UPDATE tbl_department SET location = "Waitharli Hall" WHERE name = "Department of International Relationship";
UPDATE tbl_department SET location = "Waitharli Hall" WHERE name = "Department of Archaeology";
UPDATE tbl_department SET location = "Waitharli Hall" WHERE name = "Department of History";
UPDATE tbl_department SET location = "Yamanya Hall" WHERE name = "Department of Psychology";
UPDATE tbl_department SET location = "Yamanya Hall" WHERE name = "Department of Law";
UPDATE tbl_department SET location = "Yamanya Hall" WHERE name = "Department of Philosophy";
UPDATE tbl_department SET location = "Marlar Hall" WHERE name = "Department of English";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Chemistry";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Botany";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Zoology";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Physics";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Mathematics";
UPDATE tbl_department SET location = "Art Hall" WHERE name = "Department of Oriental Studies";
UPDATE tbl_department SET location = "Art Hall" WHERE name = "Department of Geography";
UPDATE tbl_department SET location = "Mandalay Hall" WHERE name = "Department of Geology";
UPDATE tbl_department SET location = "Mandalay Hall" WHERE name = "Department of Library and Information Studies";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Anthropology";