ALTER TABLE tbl_department ADD location CHAR;
UPDATE tbl_department SET name = "Department of Mathematics" WHERE name = "Department of Mathematics ";
UPDATE tbl_department SET name = "Department of Geology" WHERE name = "Department of Geology ";
UPDATE tbl_department SET name = "Department of Geography" WHERE name = "Department of Geography ";
UPDATE tbl_department SET name = "Department of English"  WHERE name = "Department of English ";
UPDATE tbl_department SET name = "Department of International Relationship" WHERE name = "Department of International Realtionship";
UPDATE tbl_department SET name = "Department of Chemistry" WHERE name = "Department of Chemistry ";
UPDATE tbl_department SET location = "University Lab Building" WHERE name = "Department of Computer Studies";
UPDATE tbl_department SET location = "University Lab Building" WHERE name = "Department of Industrial Chemistry";
UPDATE tbl_department SET location = "Taungu Hall" WHERE name = "Department of Myanmar";
UPDATE tbl_department SET location = "Waitharli Hall" WHERE name = "Department of International Relationship";
UPDATE tbl_department SET location = "Waitharli Hall" WHERE name = "Department of Archaeology";
UPDATE tbl_department SET location = "Waitharli Hall" WHERE name = "Department of History";
UPDATE tbl_department SET location = "Yamanya Hall" WHERE name = "Department of Psychology";
UPDATE tbl_department SET location = "Yamanya Hall" WHERE name = "Department of Law";
UPDATE tbl_department SET location = "Yamanya Hall" WHERE name = "Department of Philosophy";
UPDATE tbl_department SET location = "Marlar Hall" WHERE name = "Department of English";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Chemistry";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Botany";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Zoology";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Physics";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Mathematics";
UPDATE tbl_department SET location = "Art Hall" WHERE name = "Department of Oriental Studies";
UPDATE tbl_department SET location = "Art Hall" WHERE name = "Department of Geography";
UPDATE tbl_department SET location = "Mandalay Hall" WHERE name = "Department of Geology";
UPDATE tbl_department SET location = "Mandalay Hall" WHERE name = "Department of Library and Information Studies";
UPDATE tbl_department SET location = "Science Building" WHERE name = "Department of Anthropology";